version: '2'

#Definir cada container#
services:
  #base de dados#
  db:
    image: mongo:3.0
    restart: always
    volumes:
      - data-mongodb:/data/db
    networks: 
      - network1
  
  #Servico de autorizacao#
  servicoauth:
    image: bruno/servicoauth
    ports: 
      - 3001:3001
    networks: 
      - network1
      - network2
      - network4
  
  #Servico de Email#
  servicoemail:
    image: bruno/servicoemail
    restart: always
    ports:
      - 3000:3000
    networks:
      - network2
      - network3
      - network4
  
  #Proxy de acesso
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - network4
  
  #Servidor de Emails#
  servidoremail:
    image: namshi/smtp
    restart: always
    networks:
      - network3

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge
  network4:
    driver: bridge

volumes:
  data-mongodb:
    driver: local
  