version: '1'

#Definir cada container#
services:
  #base de dados#
  db:
    image: mongo:3.0
    restart: always
    volumes:
      - /tmp/mongodb:/data/db
    networks: 
      - network1
  
  #Servico de autorizacao#
  servicoAuth:
    image: bruno/servicoauth
    networks: 
      - network1
      - network2
  
  #Servico de Email#
  servicoEmail:
    image: bruno/servicoemail
    restart: always
    networks:
      - network2
      - network3
  
  #Servidor de Emails#
  servidorEmail:
    image:
    restart: always
    networks:
      - network3

network:
  network1:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge
  