version: '3'
services:
  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
     - ~/Desktop/Universidade/VirtualizacaoRedes/TP3/topo:/home/topo
     - ~/Desktop/Universidade/VirtualizacaoRedes/TP3/clients:/home/clients
     - ~/Desktop/Universidade/VirtualizacaoRedes/TP3/dns_conf:/home/dns_conf
     - ~/Desktop/Universidade/VirtualizacaoRedes/TP3/file_servers:/home/file_servers
     - ~/Desktop/Universidade/VirtualizacaoRedes/TP3/conf_scripts:/home/conf_scripts
